function sidebar(){
 const projects=S.snapshot.projects;
 const groups=projects.map(p=>{
   const rows=S.snapshot.campaigns.filter(c=>c.project_id===p.project_id);
   const unique=rows.filter((c,i)=>rows.findIndex(x=>x.mission_id===c.mission_id)===i);
   const title=String(p.root).split(/[\\/]/).filter(Boolean).pop();
   return `<div class="project-group">${I('folder','small-icon')}${esc(title)}</div>${unique.map(c=>`<button class="task-item ${curr()?.link.mission_id===c.mission_id?'selected':''}" data-action="open-campaign" data-project="${esc(c.project_id)}" data-campaign="${esc(c.campaign_id)}"><span class="dot ${STATES[c.status]?.[1]||''}"></span><div class="grow"><div class="task-name">${esc(c.notes?c.notes.slice(0,45):'SPY 下一交易日收益研究')}</div><div class="task-note">${esc(statusName(c.status))} · ${esc(MODE_NAMES[c.mode]||c.mode)}</div></div></button>`).join('')||'<div class="side-note">尚无研究批次</div>'}`;
 }).join('');
 return `<aside class="sidebar"><div class="brand"><div class="brand-mark">${I('branch')}</div><div class="brand-name">Research<span>WORKSPACE</span></div></div>${btn('new',`${I('plus')}新建研究<span class="kbd">N</span>`,'','new-button')}<button class="nav-item ${S.view==='projects'?'active':''}" data-action="view" data-view="projects">${I('grid')}全部研究</button><button class="nav-item" data-action="search">${I('search')}查找研究<span class="grow"></span><span class="kbd">⌘ K</span></button><div class="side-label">我的项目<span class="context-label">本地</span></div><div class="side-tasks">${groups||'<div class="side-note">使用原有状态库打开项目，或创建第一项研究。</div>'}</div><div class="side-bottom"><button class="nav-item" data-action="register">${I('folder')}打开已有项目</button><button class="nav-item ${S.view==='guide'?'active':''}" data-action="view" data-view="guide">${I('book')}使用指南</button><button class="nav-item" data-action="lab">${I('flask')}高级实验室${I('slant','small-icon')}</button><button class="nav-item" data-action="legacy">${I('panel')}旧版工作区</button><button class="workspace-label text-button" data-action="settings"><span class="local-square">${I('terminal','small-icon')}</span>本地工作区 · 原状态库</button></div></aside>`
}
function topbar(){return `<div class="topbar"><div class="row"><button class="icon-button mobile-nav-button" data-action="sidebar" aria-label="打开导航">${I('menu')}</button><div class="crumbs"><span>工作区</span><span class="slash">/</span><strong>${S.view==='projects'?'全部研究':S.view==='new'?'新建研究':S.view==='guide'?'使用指南':'SPY 日频研究'}</strong></div></div><div class="connection-label"><span class="dot teal"></span>已连接本地研究引擎<button class="icon-button" data-action="refresh" aria-label="刷新状态">${I('refresh')}</button></div></div>`}
function taskHeader(){const c=curr(),p=c.payload,ds=p.campaign.dataset||{},options=p.campaign.research_options||{};const simulation=options.input_provenance?.provenance_type==='simulation_only'||String(p.scientific_claim).includes('simulation_only');return `<header class="workspace-header"><div class="title-row"><div class="grow"><h1>SPY 下一交易日收益研究</h1><p class="subtitle">${esc(c.request.options?.research_notes||'从明确的研究起点出发，让每一项实验有据可查。')}</p></div>${btn('batches',`批次 ${esc(short(p.campaign.campaign_id))}${I('down','small-icon')}`,'branch','batch-button')}</div><div class="meta-row">${badge(p.execution_status||c.task.status)}<span class="badge ${simulation?'amber':'outline'}">${simulation?'模拟数据 · 仅工程验证':'历史开发证据'}</span><span class="meta-divider"></span><button class="meta-action" data-action="drawer" data-drawer="data">${I('data','small-icon')}SPY · ${esc(ds.row_count??'—')} 行</button><span class="row">${I(c.request.advisor_mode==='live'?'bolt':'terminal','small-icon')}${esc(MODE_NAMES[c.request.advisor_mode]||c.request.advisor_mode)}</span><button class="meta-action" data-action="drawer" data-drawer="cost">${I('cpu','small-icon')}${esc(p.fit_calls??0)} 次训练预留</button></div><nav class="tabs" role="tablist" aria-label="研究视图">${[['research','研究'],['experiments','实验'],['artifacts','成果']].map(([v,t])=>`<button class="tab ${S.view===v?'active':''}" role="tab" aria-selected="${S.view===v}" data-action="view" data-view="${v}">${t}${v==='experiments'?`<span class="count">${c.candidates.length}</span>`:''}</button>`).join('')}<div class="tab-right">${selected()?`<button class="selected-chip" data-action="drawer" data-drawer="candidate">当前 <strong>${esc(short(selected().id))} · ${esc(name(selected()))}</strong>${I('panel','small-icon')}</button>`:''}<button class="text-button" data-action="drawer" data-drawer="audit">${I('shield','small-icon')}审计</button></div></nav></header>`}
function timeline(){const c=curr();const rounds=c.payload.rounds||[];const controls=c.candidates.filter(r=>r.role==='fixed_control');return `<div class="section-heading"><h2>研究过程</h2><span class="caption">${rounds.length} 批记录 · ${c.summary.research_candidates_completed} 个完成候选</span></div><div class="timeline"><div class="timeline-item"><div class="timeline-symbol">${I('stack')}</div><button class="timeline-toggle" data-action="expand" data-key="controls">建立固定对照 <span class="muted small">· ${controls.length} 个结果</span>${I(S.expanded.controls?'down':'chevron','small-icon')}</button>${S.expanded.controls?`<p class="timeline-detail">${controls.map(r=>`${esc(name(r))} <span class="mono">${fmt(r.metrics.mae)}</span>`).join(' · ')}</p>`:''}</div>${rounds.map((batch,i)=>{const key='batch'+i,open=S.expanded[key]??i===rounds.length-1;return `<div class="timeline-item"><div class="timeline-symbol ${i===rounds.length-1?'current':''}">${i+1}</div><button class="timeline-toggle" data-action="expand" data-key="${key}" data-default="${open}">第 ${esc(batch.round_index)} 批 <span class="muted small">· ${batch.items.length} 项记录</span>${I(open?'down':'chevron','small-icon')}</button>${open?batch.items.map(item=>{const h=item.hypothesis||{},id=item.candidate?.candidate_id;return `<div class="event-details"><p class="timeline-detail">${esc(h.statement||'执行记录（没有已保存的研究陈述）')}</p>${id?`<button class="candidate-inline ${c.selected_candidate_id===id?'selected':''}" data-action="candidate" data-id="${esc(id)}"><span class="candidate-id">${esc(short(id))}</span><span class="candidate-desc">${esc(MODEL_NAMES[item.candidate.model_family]||item.candidate.model_family)}</span><span class="candidate-score">${fmt(item.result?.metrics?.mae)}</span><span class="badge outline">${esc(statusName(item.status))}</span>${I('arrow','small-icon')}</button>`:`<span class="badge outline">${esc(h.action_type||'控制动作')} · ${esc(item.status)}</span>`}</div>`}).join(''):''}</div>`}).join('')}</div>`}
function researchView(){const c=curr(),p=c.payload,complete=p.execution_status==='completed';const best=c.candidates.find(r=>r.id===p.best_candidate_id);const comparison=c.best_comparison;const ref=comparison?.comparisons?.find(r=>r.reference_candidate_id===p.best_baseline_candidate_id);const relative=ref?.comparable?ref.relative_mae_improvement:null;const running=['running','starting','queued','held'].includes(c.task.status);const title=complete?(p.research_outcome==='improved'?'候选通过了开发筛选。':p.research_outcome==='no_improvement'?'研究已完成，<br><span class="soft">尚未达到开发门槛。</span>':'本轮尚无完成的研究候选。'):running?'研究正在推进。':esc(statusName(p.execution_status||c.task.status));return `<div class="reading"><div class="hero-line"><span class="hero-tick">${I(complete?'check':running?'activity':'info','small-icon')}</span>${complete?'本轮结论':'当前研究状态'}<span class="muted">/ 来自已保存记录</span></div><h2 class="hero-title">${title}</h2><p class="hero-description">${esc(c.summary.explanation)}<br><span class="small">预测下一交易日收益率，不是自动交易或未来收益承诺。</span></p>${running?`<div class="run-stats"><div class="run-stat"><small>完成研究候选 / 上限</small><strong>${c.summary.research_candidates_completed} <span>/ ${c.request.budget.max_rounds*c.request.budget.max_new_candidates_per_round}</span></strong></div><div class="run-stat"><small>训练预留 / 上限</small><strong>${p.fit_calls??0} <span>/ ${c.request.budget.max_fit_calls}</span></strong></div></div><p class="inline-guidance">候选上限不是必然完成量；状态自动读取，不触发新的研究。</p>`:`<div class="metric-strip"><div class="metric-cell"><div class="metric-label">最佳观察对象</div><div class="metric-value text">${best?esc(short(best.id)):'—'}<span>${best?esc(name(best)):''}</span></div><div class="metric-note">${best?esc(configText(best)):'尚无完整最优记录'}</div></div><div class="metric-cell"><div class="metric-label">平均绝对误差 · MAE</div><div class="metric-value">${fmt(best?.metrics.mae)}</div><div class="metric-note">历史开发窗口，非独立确认</div></div><div class="metric-cell"><div class="metric-label">相对最佳固定对照</div><div class="metric-value">${typeof relative==='number'?`${relative>=0?'↓':'↑'} ${fmt(Math.abs(relative)*100,3)}%`:'—'}</div><div class="metric-note">${best?.id===p.best_baseline_candidate_id?'最佳仍为固定对照':ref?.comparable?`参照 ${esc(short(ref.reference_candidate_id))}`:'没有可比的完整参照'}</div></div></div>`}${['waiting_provider','waiting_review','blocked','resumable'].includes(c.task.status)?`<div class="waiting-callout"><div>${I('warning')}</div><div><h3>${esc(statusName(c.task.status))}</h3><p>${esc(c.review?.status==='pending'?'需要明确审核人和批准/拒绝；不会自动继续。':c.task.blocker||p.provider_error?.error_category||'检查已记录信息后，使用对应操作。')}</p></div></div>`:''}${timeline()}</div>`}
function experimentsView(){const c=curr(),refId=c.payload.best_baseline_candidate_id;let rows=c.candidates.filter(r=>(S.filter==='all'||r.role==='research_candidate')&&`${r.id} ${name(r)} ${configText(r)}`.toLowerCase().includes(S.query.toLowerCase()));if(!S.baselines)rows=rows.filter(r=>r.role!=='fixed_control'||r.id===refId||r.id===c.selected_candidate_id);if(S.sort)rows.sort((a,b)=>(a.metrics.mae??Infinity)-(b.metrics.mae??Infinity));return `<div class="view-wrap"><h2 class="view-title">每个改变，都可以对照。</h2><p class="view-description">单击候选查看实际修改与分折结果。切换只读，不触发训练。</p><div class="table-toolbar"><div class="segmented">${[['all','全部对象'],['research','研究候选']].map(([v,t])=>`<button class="segment ${S.filter===v?'active':''}" data-action="filter" data-filter="${v}">${t}</button>`).join('')}</div><label class="search-input">${I('search')}<input id="candidate-search" value="${esc(S.query)}" placeholder="搜索模型、配置或 ID" aria-label="搜索候选"></label></div><div class="table-scroll"><table class="data-table"><thead><tr><th></th><th>候选 / 模型</th><th><button class="sort-button" data-action="sort">MAE${I('sort','small-icon')}</button></th><th>角色</th><th>执行 / 开发筛选</th></tr></thead><tbody>${rows.map(r=>`<tr data-candidate="${esc(r.id)}" data-action="candidate" data-id="${esc(r.id)}" tabindex="0" class="${c.selected_candidate_id===r.id?'selected':''}" aria-label="选择候选 ${esc(r.id)}"><td><span class="radio"></span></td><td><div class="table-name"><span class="candidate-id">${esc(short(r.id))}</span>${esc(name(r))}</div><div class="table-config">${esc(configText(r))}</div></td><td class="mono">${fmt(r.metrics.mae)}</td><td>${r.role==='fixed_control'?'固定对照':r.role==='user_start'?'用户起点':'研究候选'}${r.is_user_start&&r.role!=='user_start'?' / 用户起点':''}${r.id===c.payload.best_candidate_id?' · 最佳观察':''}</td><td>${r.status!=='completed'?esc(statusName(r.status)):r.role==='research_candidate'?(r.research_verdict==='development_screen_passed'?'<span class="badge teal">开发筛选通过</span>':'<span class="badge outline">未达开发门槛</span>'):'已完成'}</td></tr>`).join('')}</tbody></table></div>${!rows.length?'<div class="table-empty">没有符合条件的已记录对象。</div>':''}<div class="table-help"><button class="text-button" data-action="baselines">${I(S.baselines?'up':'down','small-icon')}${S.baselines?'收起其他固定对照':'展开其他固定对照'}</button><span>当前选择：${esc(short(c.selected_candidate_id))}</span></div><div class="table-disclaimer">${I('info')}改善比例与同折差值在右侧明确参照，身份不匹配时显示不可比。</div></div>`}
function artifactsView(){const c=curr(),r=selected(),records=c.refits||[],last=records.at(-1);return `<div class="view-wrap"><div class="eyebrow" style="margin-bottom:12px">RESEARCH OUTPUTS</div><h2 class="view-title">带走结果，而不丢掉依据。</h2><p class="view-description">研究记录与可加载模型分别交付，额外计算需要明确确认。</p><div class="artifact-row"><div class="artifact-icon">${I('file')}</div><div class="artifact-main"><h3>研究包</h3><p>导出实际过程、结果和证据。资料再分发受限时，由原后端生成受限版本。</p><div class="artifact-tags"><span>本批真实记录</span><span>保留原证据等级</span></div></div><div class="artifact-side">${btn('export','导出研究包','download')}<span class="status">不会运行新的研究</span></div></div><div class="artifact-row"><div class="artifact-icon">${I('cpu')}</div><div class="artifact-main"><h3>当前候选模型包</h3>${r?`<button class="candidate-binding" data-action="drawer" data-drawer="candidate">${esc(short(r.id))} · ${esc(name(r))}${I('panel','small-icon')}</button>`:''}<p>${last?'该候选已有已登记模型包，可直接下载，无需再次训练。':'使用当前候选配置额外训练 1 次，然后登记并生成模型包。不是直接下载最后一折模型。'}</p><div class="artifact-tags"><span>候选与 refit ID 校验</span><span>本机可信登记</span></div></div><div class="artifact-side">${last?btn('download-model','下载当前模型包','download','primary',`data-refit="${esc(last.refit_id)}"`):btn('refit','生成模型包','cpu','primary',c.deliverable?'':'disabled')}<span class="status">${last?'已生成 · '+esc(short(last.refit_id)):c.deliverable?'额外 1 次训练，费用独立记录':'需要已完成批次中的已接受估计器'}</span></div></div><div class="continuation-strip"><div><h3>从这个候选继续研究</h3><p>继承起点与冻结数据，新增批次和预算；不是免费恢复。</p></div>${btn('continue','查看续接配置','branch','',c.deliverable&&c.request.advisor_mode!=='replay'?'':'disabled')}</div><div class="security-line">${I('shield','small-icon')}下载成功不表示独立确认、生产部署或跨机器信任迁移。</div></div>`}
function drawer(){if(!S.drawer||!curr())return '';const c=curr(),r=selected(),p=c.payload;let title='',body='';
 if(S.drawer==='candidate'&&r){title='候选审阅';const comps=c.comparison?.comparisons||[];body=`<div class="drawer-identifier"><span class="candidate-id">${esc(short(r.id))}</span><h2>${esc(name(r))}</h2></div><p class="drawer-subtitle">${esc(configText(r))}</p>${kv('完整候选 ID',r.id)}${priceCandidateDetail(r)}<div class="drawer-section"><h3>实际修改</h3>${r.config_diff?.changes?.length?r.config_diff.changes.map(d=>`<div class="diff-row"><span>${esc(d.path)}</span></div><div class="row small actual-diff"><span class="diff-old">${esc(JSON.stringify(d.old_value))}</span>${I('arrow','small-icon')}<span class="diff-new">${esc(JSON.stringify(d.new_value))}</span></div>`).join(''):'<p>固定起点或没有已记录的参数改动。</p>'}${kv('参数差异参照',r.candidate.parent_candidate_id||'无父候选')}</div><div class="drawer-section"><h3>实际结果与明确参照</h3><div class="drawer-score">${fmt(r.metrics.mae)}</div>${comps.map(v=>`<div class="kv"><span>相对 ${esc(short(v.reference_candidate_id))}</span><span class="${v.comparable?'accent':'incomparable'}">${v.comparable&&typeof v.relative_mae_improvement==='number'?`${fmt(v.relative_mae_improvement*100,3)}% MAE 改善`:'不可比 / 未知'}</span></div>`).join('')}<p>正值表示误差降低，不等于达到开发门槛。</p></div><div class="drawer-section"><h3>历史开发窗口</h3>${r.fold_metrics.map(f=>kv('窗口 '+f.fold_id,`MAE ${fmt(f.mae)} · ${f.test_count??'—'} 个目标`)).join('')}<p>不是四次独立确认。</p></div><div class="drawer-section"><h3>已记录的研究提案</h3><p>${esc(r.hypothesis?.statement||'未记录')}</p>${r.hypothesis?.mechanism?`<p>${esc(r.hypothesis.mechanism)}</p>`:''}<p class="muted">提案陈述不替代上方实际参数和指标。</p>${r.hypothesis?.literature_uses?.length?btn('drawer','查看关联文献','book','sm','data-drawer="literature"'):''}</div>${r.feedback?`<details class="event-details"><summary>确定性反馈</summary>${jsonView(r.feedback)}</details>`:''}`;
 }else if(S.drawer==='data'){title='数据与任务';const ds=p.campaign.dataset||{};body=`<h2 class="view-title">SPY · 日频</h2>${kv('有效行数',ds.row_count)}${kv('时间范围',`${ds.start_date||'未知'} → ${ds.end_date||'未知'}`)}${kv('来源',ds.source_name)}${kv('许可状态',ds.license_status)}${kv('曝光',ds.exposure)}${kv('原始文件',c.request.raw_path)}<div class="drawer-section"><h3>任务与核验</h3>${jsonView({task:p.campaign.task,input_verification:p.input_verification||p.campaign.research_options?.input_provenance||'没有额外输入核验记录'})}</div><details class="event-details"><summary>数据身份</summary>${jsonView(ds)}</details>`;
 }else if(S.drawer==='literature'){title='文献与实验依据';const papers=c.summary.literature||[];body=papers.length?papers.map(v=>`<div class="drawer-section"><h3>${esc(v.review_id)}</h3>${jsonView({author_fact:v.paper_fact,conditions:v.conditions,limitations:v.limitations,local_decisions:v.local_decisions,not_used_reason:v.not_used_reason})}</div>`).join(''):'<p class="drawer-subtitle">本批没有选用已审核文献。没有资料也能基础研究。</p>';
 }else if(S.drawer==='cost'){title='资源与费用';body=`<h2 class="view-title">成本分开记录</h2>${kv('本批训练预留',p.fit_calls)}${kv('已完成研究候选',c.summary.research_candidates_completed)}${kv('历史研究训练',c.summary.cost.prior_research_fit_calls)}${kv('本批显式 refit',c.summary.cost.current_explicit_refit_calls)}${p.resource_usage?.feature_planning?`<div class="drawer-section"><h3>价格特征规划账本</h3>${jsonView(p.resource_usage.feature_planning)}<p>逻辑规划、Advisor尝试、HTTP与fit不是同一计数；未知费用不计零。</p></div>`:''}${kv('货币费用','未知；不计为零')}<div class="drawer-section"><h3>本批资源上限</h3>${jsonView(c.request.budget)}</div><details class="event-details"><summary>账本用量</summary>${jsonView(c.summary.cost)}</details>`;
 }else{title='技术审计';body=`${kv('批次 ID',p.campaign.campaign_id)}${kv('执行状态',p.execution_status)}${kv('研究结论',p.research_outcome)}${kv('终止原因',p.stop_reason)}${kv('开发筛选通过',p.development_screen_passed??'旧记录未分列')}<div class="drawer-section"><h3>任务、协议与证据边界</h3>${jsonView({task:p.campaign.task,evaluation_policy:p.evaluation_policy||p.campaign.evaluation_policy,split:p.split_spec||p.campaign.split_spec,evidence_status:p.evidence_status,execution_contract_hash:p.execution_contract_hash})}</div><details class="event-details"><summary>最近 100 项事件摘要</summary>${jsonView(c.events)}</details>${p.error_facts?jsonView(p.error_facts):''}`}
 return `<button class="drawer-overlay-close" data-action="close-drawer" aria-label="关闭详情"></button><aside class="drawer"><div class="drawer-head"><span class="drawer-title">${I('panel','small-icon')}${title}</span><button class="icon-button" data-action="close-drawer" aria-label="关闭详情">${I('close')}</button></div><div class="drawer-content">${body}</div><div class="drawer-foot">只读审阅 · 不运行训练或新的模型调用</div></aside>`
}
function dock(){const c=curr();if(!c)return '';let controls='';const status=c.task.status;if(status==='waiting_review'&&c.review?.status==='pending'){controls=btn('review-approve','审核并批准','check','primary')+btn('review-reject','拒绝','close','danger')}else if(['waiting_provider','waiting_review','resumable','held'].includes(status)){controls=btn('resume','检查并恢复','refresh','primary')}else if(['running','starting','queued'].includes(status)){controls=btn('cancel','取消研究','stop','danger')}else{controls=btn('view',S.view==='artifacts'?'查看实验':'查看成果',S.view==='artifacts'?'grid':'arrow','primary',`data-view="${S.view==='artifacts'?'experiments':'artifacts'}"`)}return `<div class="dock"><div class="dock-copy"><strong>${esc(statusName(c.payload.execution_status||status))} · ${esc(MODE_NAMES[c.request.advisor_mode])}</strong><span>当前 ${esc(short(c.selected_candidate_id))||'无候选'} · 开发证据与独立确认分开</span></div><div class="dock-actions">${controls}</div></div>`}
function taskWorkspace(){return `${taskHeader()}<div class="content-shell"><div class="main-pane"><main class="main-scroll">${notices()}${S.view==='experiments'?experimentsView():S.view==='artifacts'?artifactsView():researchResultRoles(curr())+researchView()}</main>${dock()}</div>${drawer()}</div>`}
function notices(){return `${S.uncertain?'<div class="op-warning">上一次页面操作未确认返回。请先查看最新任务或模型包记录，不要重复发起训练。</div>':''}${S.error?`<div class="live-error" role="alert">${esc(S.error)}</div>`:''}${(S.snapshot.errors||[]).map(e=>`<div class="live-error" role="alert">${esc(e)}</div>`).join('')}`}
function projectsView(){const rows=S.snapshot.campaigns.filter(c=>`${c.notes} ${c.question} ${c.campaign_id}`.toLowerCase().includes(S.query.toLowerCase()));return `<div class="content-shell"><main class="main-scroll">${notices()}<div class="list-header"><div><div class="eyebrow" style="margin-bottom:12px">YOUR RESEARCH</div><h1>回到问题，继续研究。</h1><p>真实任务、实际实验与已登记成果，来自同一个本地工作区。</p></div>${btn('new','新建研究','plus','primary')}</div><div class="projects-list"><div class="row spread" style="padding-bottom:14px;border-bottom:1px solid var(--line)"><span class="small subtle">${rows.length} 个研究批次</span><label class="search-input">${I('search')}<input id="project-search" aria-label="查找研究" placeholder="查找研究" value="${esc(S.query)}"></label></div>${rows.map(c=>`<div class="project-row" data-action="open-campaign" data-project="${esc(c.project_id)}" data-campaign="${esc(c.campaign_id)}" role="button" tabindex="0"><div class="project-mark">${I('branch')}</div><div class="project-text grow"><strong>${esc(c.notes?c.notes.slice(0,70):'SPY 下一交易日收益研究')}</strong><p>${esc(short(c.campaign_id))} · ${esc(MODE_NAMES[c.mode])} · ${esc(c.updated_at?.slice(0,16).replace('T',' ')||'')}</p></div><div class="project-meta">${badge(c.status)}${I('chevron')}</div></div>`).join('')||`<div class="empty-state"><div class="empty-symbol">${I('flask')}</div><h2>从一个明确的研究开始。</h2><p>没有现成模型也可以开始，但需要合法本地数据。已有研究未显示时，请先检查启动环境是否指向原来的状态数据库。</p>${btn('new','创建第一项研究','plus','primary')}</div>`}<div class="welcome-inline"><div><h3>从数据到结果，不改变研究边界</h3><p>固定 SPY 任务 · 受支持模型 · 真实实验记录 · 明确追加计算</p></div>${btn('view','使用指南','arrow','subtle-button','data-view="guide"')}</div></div></main></div>`}
function guideView(){return `<div class="content-shell"><main class="main-scroll"><div class="reading"><div class="eyebrow">WORKSPACE GUIDE</div><h2 class="view-title" style="margin-top:18px">主线清楚，细节随时可查。</h2>${[['研究','默认阅读当前结论与实际执行过程。参数配置不混在结果页面中。'],['实验','选择一行，右侧查看实际修改、分折结果与明确参照。只有可比结果才显示改善比例。'],['成果','研究包导出证据；模型包明确额外训练一次。已生成的当前候选模型包可以直接下载，不会重新训练。'],['模式','规则演示不是大模型；真实LLM需要明确费用与资料发送确认；离线回放需要匹配旧源码、环境和明确调用ID。'],['继续与恢复','继续研究创建有父候选的新Campaign，新增预算；故障恢复仍受原冻结合同和录制中断防重发限制。'],['数据与权限','使用启动环境指定的原RuntimeDB。页面不提供任意模型文件执行，不重置曝光，不创建金融确认授权。'],['兼容入口','左侧保留旧版工作区和高级实验室。新界面没有增加研究引擎、API服务或另一套状态库。']].map(([t,p])=>`<section class="guide-section"><h3>${t}</h3><p>${p}</p></section>`).join('')}</div></main></div>`}
function priceCandidateDetail(r){if(!r.candidate.feature_program)return '';let formulas;try{formulas=r.candidate.feature_program.features.map(f=>kv(f.name,priceFormula(f.expression))).join('')||'<p>无新增价格公式。</p>'}catch(_){formulas='<p>无法展示公式；请核查已保存的 AST。</p>'}return `<div class="drawer-section" data-testid="price-program"><h3>实际价格公式（只读）</h3><div data-testid="readable-formula">${formulas}</div><details><summary>原始 AST</summary>${jsonView(r.candidate.feature_program)}</details>${kv('实际列顺序',(r.actual_features||[]).join(', '))}${kv('模型回看长度',r.feature_execution?.lookback)}${kv('保护除法次数',JSON.stringify(r.feature_execution?.protected_divisions??{}))}<p>生成式建议不是执行权限；公式由有界计算器执行。当前协议禁止独立确认。</p></div>`}

function priceFormula(node,depth=1){
 if(!node||typeof node!=='object'||depth>4)throw Error('Invalid saved formula');
 const op=node.op, sub=n=>priceFormula(n,depth+1);
 if(op==='input'&&node.name==='return_1')return 'return_1';
 if(['add','subtract','multiply','safe_divide'].includes(op))return `${op}(${sub(node.left)}, ${sub(node.right)})`;
 if(op==='abs')return `abs(${sub(node.arg)})`;
 const value=op==='lag'?node.periods:node.window;
 const allowed=op==='lag'?[1,2,5,10,20]:['rolling_mean','rolling_std'].includes(op)?[2,5,10,20,60]:[];
 if(!Number.isInteger(value)||!allowed.includes(value))throw Error('Invalid saved operator');
 return `${op}(${sub(node.arg)}, ${value})`;
}
function researchResultRoles(c){
 if(!c)return '';
 const rows=(c.candidates||[]).filter(r=>r.status==='completed'&&Number.isFinite(r.metrics?.mae));
 const best=list=>list.reduce((a,b)=>!a||b.metrics.mae<a.metrics.mae?b:a,null);
 const research=best(rows.filter(r=>r.role==='research_candidate'));
 const baseline=best(rows.filter(r=>r.role==='fixed_control'));
 const start=rows.find(r=>r.is_user_start||r.role==='user_start');
 const available=best(rows), label=r=>r?`${r.id} · MAE ${fmt(r.metrics.mae)}`:'无已完成结果';
 return `<section class="reading drawer-section" data-testid="research-result-roles"><h3>结果角色</h3>${kv('最佳研究候选',label(research))}${kv('最佳固定对照',label(baseline))}${kv('用户起点',label(start))}${kv('最佳可用模型（含对照）',label(available))}${research?'<p>开发集观察，不代表独立确认或盈利。</p>':'<p>未评估研究效果：没有已完成研究候选；基线结果不能替代研究结果。</p>'}</section>`;
}

