from __future__ import annotations

from .schemas import PaperSpecCard


def built_in_paper_specs() -> list[PaperSpecCard]:
    """Curated US-equity / stock-return ML paper specs for no-key golden tests.

    These specs are not a claim that the project contains each paper's original data.
    They are paper-protocol cards used to test strict-vs-exploratory routing,
    ReplayLLM fixture generation, candidate contracts, and finance evaluation.
    """
    return [
        PaperSpecCard(
            paper_id="rf_technical_indicators_spy",
            title="Assessing the Impact of Technical Indicators on Machine Learning Models for Stock Price Prediction",
            venue_or_source="arXiv / applied ML finance paper",
            paper_url="https://arxiv.org/pdf/2412.15448.pdf",
            target_asset="AAPL",
            asset_universe=["AAPL", "SPY"],
            frequency="daily",
            horizon="next_return",
            label_definition="next_return",
            required_feature_groups=["price_lag_features", "return_momentum_features", "volatility_features"],
            required_model_families=["random_forest_regressor"],
            required_metrics=["mae", "rmse", "directional_accuracy", "net_return"],
            required_split="purged_walk_forward",
            min_rows=250,
            original_dataset_required=True,
            exact_model_required=True,
            notes="Technical-indicator baseline. Local panel is a real but substituted weekly US-equity dataset.",
            evidence_spans=[{"field": "model", "summary": "Random forest and technical indicators are central to the paper protocol."}],
        ),
        PaperSpecCard(
            paper_id="fischer_krauss_lstm_sp500",
            title="Deep learning with long short-term memory networks for financial market predictions",
            venue_or_source="European Journal of Operational Research / S&P 500 stock universe",
            paper_url="https://doi.org/10.1016/j.ejor.2017.11.054",
            target_asset="AAPL",
            asset_universe=["AAPL", "MSFT", "SPY", "S&P500"],
            frequency="daily",
            horizon="next_return_direction",
            label_definition="next_return",
            required_feature_groups=["sequence_window_features", "return_momentum_features"],
            required_model_families=["lstm_regressor"],
            required_metrics=["directional_accuracy", "net_return", "sharpe"],
            required_split="purged_walk_forward",
            min_rows=500,
            original_dataset_required=True,
            exact_model_required=True,
            notes="High-impact deep learning S&P 500 direction prediction paper; local run uses AAPL panel as exploratory substitute.",
            evidence_spans=[{"field": "model", "summary": "LSTM is the paper-family model."}],
        ),
        PaperSpecCard(
            paper_id="krauss_do_huck_dnn_gbt_rf_stat_arb",
            title="Deep neural networks, gradient-boosted trees, random forests: Statistical arbitrage on the S&P 500",
            venue_or_source="European Journal of Operational Research",
            paper_url="https://doi.org/10.1016/j.ejor.2016.10.031",
            target_asset="AAPL",
            asset_universe=["AAPL", "MSFT", "SPY", "S&P500"],
            frequency="daily",
            horizon="next_return_cross_section",
            label_definition="next_return",
            required_feature_groups=["return_momentum_features", "cross_asset_features", "volatility_features"],
            required_model_families=["gradient_boosting_regressor", "random_forest_regressor"],
            required_metrics=["net_return", "sharpe", "directional_accuracy"],
            required_split="purged_walk_forward",
            min_rows=500,
            original_dataset_required=True,
            exact_model_required=False,
            notes="S&P 500 statistical-arbitrage benchmark with DNN/GBT/RF; current harness tests tree candidates on local panel.",
            evidence_spans=[{"field": "models", "summary": "Gradient-boosted trees and random forests are paper-family candidates."}],
        ),
        PaperSpecCard(
            paper_id="gu_kelly_xiu_empirical_asset_pricing_ml",
            title="Empirical Asset Pricing via Machine Learning",
            venue_or_source="Review of Financial Studies",
            paper_url="https://academic.oup.com/rfs/article/33/5/2223/5758276",
            target_asset="AAPL",
            asset_universe=["AAPL", "MSFT", "SPY", "US equities"],
            frequency="monthly",
            horizon="next_return",
            label_definition="next_return",
            required_feature_groups=["return_momentum_features", "cross_asset_features", "volatility_features"],
            required_model_families=["random_forest_regressor", "gradient_boosting_regressor", "ridge_regression"],
            required_metrics=["r2", "net_return", "sharpe"],
            required_split="purged_walk_forward",
            min_rows=1000,
            original_dataset_required=True,
            exact_model_required=False,
            notes="Canonical ML asset-pricing paper; strict replication needs CRSP/Compustat-style characteristics and monthly panels.",
            evidence_spans=[{"field": "data", "summary": "Broad US equity panel and firm characteristics are required for strict replication."}],
        ),
        PaperSpecCard(
            paper_id="kelly_malamud_zhou_virtue_complexity",
            title="The Virtue of Complexity in Return Prediction",
            venue_or_source="Journal of Finance / working-paper lineage",
            paper_url="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3984925",
            target_asset="AAPL",
            asset_universe=["AAPL", "MSFT", "SPY", "US equities"],
            frequency="monthly",
            horizon="next_return",
            label_definition="next_return",
            required_feature_groups=["return_momentum_features", "cross_asset_features", "volatility_features"],
            required_model_families=["gradient_boosting_regressor", "random_forest_regressor"],
            required_metrics=["r2", "net_return", "sharpe"],
            required_split="purged_walk_forward",
            min_rows=1000,
            original_dataset_required=True,
            exact_model_required=False,
            notes="Complexity-vs-return-prediction benchmark; local test checks whether scheduler/audit handles complex candidates without over-claiming.",
            evidence_spans=[{"field": "risk", "summary": "High model complexity requires strict out-of-sample and cost-aware evaluation."}],
        ),
        PaperSpecCard(
            paper_id="gu_kelly_xiu_deep_learning_asset_pricing",
            title="Deep Learning in Asset Pricing",
            venue_or_source="asset pricing / deep learning research line",
            paper_url="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3350138",
            target_asset="AAPL",
            asset_universe=["AAPL", "MSFT", "SPY", "US equities"],
            frequency="monthly",
            horizon="next_return",
            label_definition="next_return",
            required_feature_groups=["sequence_window_features", "return_momentum_features", "cross_asset_features"],
            required_model_families=["transformer_regressor", "lstm_regressor"],
            required_metrics=["r2", "net_return", "sharpe"],
            required_split="purged_walk_forward",
            min_rows=1000,
            original_dataset_required=True,
            exact_model_required=True,
            notes="Deep-learning asset-pricing protocol; current project runs lightweight sequence adapters but still blocks strict without paper data.",
            evidence_spans=[{"field": "model", "summary": "Deep sequence / neural return prediction is central."}],
        ),
        PaperSpecCard(
            paper_id="ghosh_neufeld_sahoo_intraday_lstm_rf",
            title="Forecasting directional movements of stock prices for intraday trading using LSTM and random forests",
            venue_or_source="arXiv / S&P 500 intraday direction prediction",
            paper_url="https://arxiv.org/abs/2004.10178",
            target_asset="AAPL",
            asset_universe=["AAPL", "MSFT", "S&P500"],
            frequency="intraday",
            horizon="intraday_direction",
            label_definition="next_return",
            required_feature_groups=["sequence_window_features", "return_momentum_features", "volatility_features"],
            required_model_families=["lstm_regressor", "random_forest_regressor"],
            required_metrics=["directional_accuracy", "net_return", "turnover"],
            required_split="purged_walk_forward",
            min_rows=2000,
            original_dataset_required=True,
            exact_model_required=True,
            notes="Intraday paper; local weekly data is intentionally exploratory only.",
            evidence_spans=[{"field": "data", "summary": "Strict test requires intraday open/close/intraday return fields."}],
        ),
        PaperSpecCard(
            paper_id="ga_lstm_stock_prediction",
            title="Time Series Stock Price Forecasting Based on Genetic Algorithm (GA)-LSTM Optimization",
            venue_or_source="arXiv",
            paper_url="https://arxiv.org/abs/2405.03151",
            target_asset="AAPL",
            asset_universe=["AAPL"],
            frequency="daily",
            horizon="next_return",
            label_definition="next_return",
            required_feature_groups=["sequence_window_features", "return_momentum_features"],
            required_model_families=["ga_lstm_regressor"],
            required_metrics=["mae", "rmse", "r2"],
            required_split="purged_walk_forward",
            min_rows=500,
            original_dataset_required=True,
            exact_model_required=True,
            notes="This project implements a real GA-LSTM adapter, not an MLP proxy.",
            evidence_spans=[{"field": "model", "summary": "GA hyperparameter search wraps an LSTM model."}],
        ),
        PaperSpecCard(
            paper_id="transformer_stock_prediction",
            title="Comparative Analysis of LSTM, GRU, and Transformer Models for Stock Price Prediction",
            venue_or_source="arXiv / deep sequence stock prediction",
            paper_url="https://arxiv.org/abs/2411.05790",
            target_asset="AAPL",
            asset_universe=["AAPL"],
            frequency="daily",
            horizon="next_return",
            label_definition="next_return",
            required_feature_groups=["sequence_window_features", "return_momentum_features", "cross_asset_features"],
            required_model_families=["lstm_regressor", "transformer_regressor"],
            required_metrics=["mae", "rmse", "directional_accuracy"],
            required_split="purged_walk_forward",
            min_rows=500,
            original_dataset_required=True,
            exact_model_required=True,
            notes="Sequence comparison; local harness supports LSTM and Transformer adapters.",
            evidence_spans=[{"field": "model", "summary": "LSTM and Transformer are paper-family candidates."}],
        ),
        PaperSpecCard(
            paper_id="filipovic_pasricha_egpr_asset_pricing",
            title="Empirical Asset Pricing via Ensemble Gaussian Process Regression",
            venue_or_source="arXiv / empirical asset pricing",
            paper_url="https://arxiv.org/abs/2212.01048",
            target_asset="AAPL",
            asset_universe=["AAPL", "MSFT", "SPY", "US equities"],
            frequency="monthly",
            horizon="next_return",
            label_definition="next_return",
            required_feature_groups=["return_momentum_features", "cross_asset_features", "volatility_features"],
            required_model_families=["ridge_regression", "gradient_boosting_regressor"],
            required_metrics=["r2", "net_return", "sharpe"],
            required_split="purged_walk_forward",
            min_rows=1000,
            original_dataset_required=True,
            exact_model_required=False,
            notes="GPR paper is represented by uncertainty-aware/regression baselines until a GPR adapter is added.",
            evidence_spans=[{"field": "future_work", "summary": "Add gaussian_process_regressor adapter for closer protocol matching."}],
        ),
        PaperSpecCard(
            paper_id="freyberger_neuhierl_weber_characteristics_nonparametric",
            title="Dissecting Characteristics Nonparametrically",
            venue_or_source="Review of Financial Studies / stock characteristics",
            paper_url="https://academic.oup.com/rfs/article/33/5/2326/5732816",
            target_asset="AAPL",
            asset_universe=["AAPL", "MSFT", "SPY", "US equities"],
            frequency="monthly",
            horizon="next_return",
            label_definition="next_return",
            required_feature_groups=["return_momentum_features", "cross_asset_features"],
            required_model_families=["gradient_boosting_regressor", "ridge_regression"],
            required_metrics=["r2", "net_return", "sharpe"],
            required_split="purged_walk_forward",
            min_rows=1000,
            original_dataset_required=True,
            exact_model_required=False,
            notes="Nonparametric characteristics paper; strict version needs full characteristic panel.",
            evidence_spans=[{"field": "data", "summary": "Strict replication requires firm characteristics, not only price panel."}],
        ),
        PaperSpecCard(
            paper_id="rapach_strauss_zhou_industry_returns",
            title="Out-of-Sample Equity Premium Prediction: Combination Forecasts and Links to the Real Economy / Industry return predictability line",
            venue_or_source="Review of Financial Studies / Journal of Financial Economics related forecasting literature",
            paper_url="https://academic.oup.com/rfs/article/23/2/821/1589817",
            target_asset="SPY",
            asset_universe=["SPY", "AAPL", "MSFT", "US equities"],
            frequency="monthly",
            horizon="next_return",
            label_definition="next_return",
            required_feature_groups=["cross_asset_features", "return_momentum_features"],
            required_model_families=["ridge_regression", "random_forest_regressor"],
            required_metrics=["r2", "net_return", "sharpe"],
            required_split="purged_walk_forward",
            min_rows=500,
            original_dataset_required=True,
            exact_model_required=False,
            notes="Forecast combination / industry-link benchmark. Local panel can only test cross-asset proxy ideas.",
            evidence_spans=[{"field": "feature", "summary": "Cross-asset or industry-return predictors motivate cross_asset_features."}],
        ),
    ]
