from __future__ import annotations

from .schemas import PaperSpecCard


def built_in_paper_specs() -> list[PaperSpecCard]:
    return [
        PaperSpecCard(
            paper_id='rf_technical_indicators_spy',
            title='Assessing the Impact of Technical Indicators on Machine Learning Models for Stock Price Prediction',
            venue_or_source='arXiv / applied ML finance paper',
            paper_url='https://arxiv.org/pdf/2412.15448.pdf',
            target_asset='AAPL',
            asset_universe=['AAPL','SPY'],
            frequency='daily',
            horizon='next_return',
            label_definition='next_return',
            required_feature_groups=['price_lag_features','return_momentum_features','volatility_features'],
            required_model_families=['random_forest_regressor'],
            required_metrics=['mae','rmse','directional_accuracy','net_return'],
            required_split='purged_walk_forward',
            min_rows=250,
            original_dataset_required=True,
            exact_model_required=True,
            notes='Paper-inspired technical-indicator baseline. Local data is a real but substituted weekly US-equity panel.',
        ),
        PaperSpecCard(
            paper_id='ga_lstm_stock_prediction',
            title='Time Series Stock Price Forecasting Based on Genetic Algorithm (GA)-LSTM Optimization',
            venue_or_source='arXiv',
            paper_url='https://arxiv.org/abs/2405.03151',
            target_asset='AAPL',
            asset_universe=['AAPL'],
            frequency='daily',
            horizon='next_return',
            label_definition='next_return',
            required_feature_groups=['sequence_window_features','return_momentum_features'],
            required_model_families=['ga_lstm_regressor'],
            required_metrics=['mae','rmse','r2'],
            required_split='purged_walk_forward',
            min_rows=500,
            original_dataset_required=True,
            exact_model_required=True,
            notes='Deep sequence method. This project implements an actual GA-LSTM adapter, not an MLP proxy.',
        ),
        PaperSpecCard(
            paper_id='transformer_stock_prediction',
            title='Comparative Analysis of LSTM, GRU, and Transformer Models for Stock Price Prediction',
            venue_or_source='arXiv',
            paper_url='https://arxiv.org/abs/2411.05790',
            target_asset='AAPL',
            asset_universe=['AAPL'],
            frequency='daily',
            horizon='next_return',
            label_definition='next_return',
            required_feature_groups=['sequence_window_features','return_momentum_features','cross_asset_features'],
            required_model_families=['lstm_regressor','transformer_regressor'],
            required_metrics=['mae','rmse','directional_accuracy'],
            required_split='purged_walk_forward',
            min_rows=500,
            original_dataset_required=True,
            exact_model_required=True,
            notes='Deep sequence comparison. Local harness supports LSTM and Transformer adapters.',
        ),
    ]
